services:
    # Déclare automatiquement tous les services du bundle
    ExcelFormulaBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'